name: gh-pages deploy

on:
  push:
    branches: [ "main" ]
    
jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false
    - name: Setup pnpm
      run: |

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
            ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm install --frozen-lockfile    
    - name: Build App
      run: |
        export SITE_DOMAIN="https://willwill96.github.io",
        export BASE_URL="/spotify-song-deduplication"
        pnpm build
        export PNPM_HOME="/home/runner/.local/share/pnpm"
        SHELL=$SHELL pnpm setup
        export PATH="$PNPM_HOME:$PATH"
        source /home/runner/.bashrc
        pnpm add -g gh-pages
        git config user.name github-action
        git config user.email github-actions@github.com
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        pnpm gh-pages -d dist/